name: aliuai_painel
description: "Painel do Parceiro AliUai"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  url_launcher: ^6.3.2
  firebase_storage: ^13.4.1
  file_picker: ^10.2.0
  url_strategy: ^0.3.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  http: ^1.6.0  
  html_editor_enhanced: ^2.7.1
  flutter_native_splash: ^2.4.7
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  cropperx: ^1.1.1
  pointer_interceptor: ^0.10.1+2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  fl_chart: ^0.66.0
  audioplayers: ^6.7.1
  font_awesome_flutter: ^11.0.0
  package_info_plus: ^9.0.1
  flutter_html: ^3.0.0    
  crop_your_image: ^2.0.0
  mask_text_input_formatter: ^2.9.0
  blue_thermal_printer: ^1.2.3
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/logo/logo_aliuai.png
    - assets/sounds/notificacao.mp3
    - assets/sounds/chat.mp3

flutter_native_splash:
  # 1. A cor de fundo da tela inteira (o fundo escuro do Aliuai)
  color: "#1E1E26"
  
  # 2. O caminho para a imagem do seu logo
  image: assets/logo/logo_aliuai.png
  
  # 3. Configurações extras para Android 12+ (Obrigatório para sistemas novos)
  android_12:
    image: assets/logo/logo_aliuai.png
    color: "#1E1E26"
    
  # Garante que o splash preencha a tela corretamente em modo tela cheia
  fullscreen: true