import 'package:flutter/material.dart';

class SeletorIconesModal extends StatefulWidget {
  final Function(int codePoint, String nomeIcone) onIconeSelecionado;

  const SeletorIconesModal({super.key, required this.onIconeSelecionado});

  @override
  State<SeletorIconesModal> createState() => _SeletorIconesModalState();
}

class _SeletorIconesModalState extends State<SeletorIconesModal> {
  final TextEditingController _buscaController = TextEditingController();
  String _filtro = '';

  // 📚 Todos os ícones clássicos e estáveis do Flutter mapeados pelo nome!
  final Map<String, IconData> _iconesDisponiveis = {
    'church_outlined': Icons.church_outlined,
    'church': Icons.church,
    'museum': Icons.museum,
    'museum_outlined': Icons.museum_outlined,
    'computer_outlined': Icons.computer_outlined,
    'laptop_mac': Icons.laptop_mac,
    'design_services': Icons.design_services,
    'ac_unit': Icons.ac_unit,
    'access_alarm': Icons.access_alarm,
    'access_alarms': Icons.access_alarms,
    'access_time': Icons.access_time,
    'accessibility': Icons.accessibility,
    'accessibility_new': Icons.accessibility_new,
    'accessible': Icons.accessible,
    'accessible_forward': Icons.accessible_forward,
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'account_box': Icons.account_box,
    'account_circle': Icons.account_circle,
    'adb': Icons.adb,
    'add': Icons.add,
    'add_a_photo': Icons.add_a_photo,
    'add_alarm': Icons.add_alarm,
    'add_alert': Icons.add_alert,
    'add_box': Icons.add_box,
    'add_circle': Icons.add_circle,
    'add_circle_outline': Icons.add_circle_outline,
    'add_location': Icons.add_location,
    'add_shopping_cart': Icons.add_shopping_cart,
    'add_to_home_screen': Icons.add_to_home_screen,
    'add_to_photos': Icons.add_to_photos,
    'add_to_queue': Icons.add_to_queue,
    'adjust': Icons.adjust,
    'airline_seat_flat': Icons.airline_seat_flat,
    'airline_seat_flat_angled': Icons.airline_seat_flat_angled,
    'airline_seat_individual_suite': Icons.airline_seat_individual_suite,
    'airline_seat_legroom_extra': Icons.airline_seat_legroom_extra,
    'airline_seat_legroom_normal': Icons.airline_seat_legroom_normal,
    'airline_seat_legroom_reduced': Icons.airline_seat_legroom_reduced,
    'airline_seat_recline_extra': Icons.airline_seat_recline_extra,
    'airline_seat_recline_normal': Icons.airline_seat_recline_normal,
    'airplanemode_active': Icons.airplanemode_active,
    'airplanemode_inactive': Icons.airplanemode_inactive,
    'airplay': Icons.airplay,
    'airport_shuttle': Icons.airport_shuttle,
    'alarm': Icons.alarm,
    'alarm_add': Icons.alarm_add,
    'alarm_off': Icons.alarm_off,
    'alarm_on': Icons.alarm_on,
    'album': Icons.album,
    'all_inclusive': Icons.all_inclusive,
    'all_out': Icons.all_out,
    'alternate_email': Icons.alternate_email,
    'android': Icons.android,
    'announcement': Icons.announcement,
    'apps': Icons.apps,
    'archive': Icons.archive,
    'arrow_back': Icons.arrow_back,
    'arrow_back_ios': Icons.arrow_back_ios,
    'arrow_downward': Icons.arrow_downward,
    'arrow_drop_down': Icons.arrow_drop_down,
    'arrow_drop_down_circle': Icons.arrow_drop_down_circle,
    'arrow_drop_up': Icons.arrow_drop_up,
    'arrow_forward': Icons.arrow_forward,
    'arrow_forward_ios': Icons.arrow_forward_ios,
    'arrow_left': Icons.arrow_left,
    'arrow_right': Icons.arrow_right,
    'arrow_upward': Icons.arrow_upward,
    'art_track': Icons.art_track,
    'aspect_ratio': Icons.aspect_ratio,
    'assessment': Icons.assessment,
    'assignment': Icons.assignment,
    'assignment_ind': Icons.assignment_ind,
    'assignment_late': Icons.assignment_late,
    'assignment_return': Icons.assignment_return,
    'assignment_returned': Icons.assignment_returned,
    'assignment_turned_in': Icons.assignment_turned_in,
    'assistant': Icons.assistant,
    'assistant_photo': Icons.assistant_photo,
    'atm': Icons.atm,
    'attach_file': Icons.attach_file,
    'attach_money': Icons.attach_money,
    'attachment': Icons.attachment,
    'audiotrack': Icons.audiotrack,
    'autorenew': Icons.autorenew,
    'av_timer': Icons.av_timer,
    'backspace': Icons.backspace,
    'backup': Icons.backup,
    'ballot': Icons.ballot,
    'bar_chart': Icons.bar_chart,
    'bathtub': Icons.bathtub,
    'battery_alert': Icons.battery_alert,
    'battery_charging_full': Icons.battery_charging_full,
    'battery_full': Icons.battery_full,
    'battery_std': Icons.battery_std,
    'battery_unknown': Icons.battery_unknown,
    'beach_access': Icons.beach_access,
    'beenhere': Icons.beenhere,
    'block': Icons.block,
    'bluetooth': Icons.bluetooth,
    'bluetooth_audio': Icons.bluetooth_audio,
    'bluetooth_connected': Icons.bluetooth_connected,
    'bluetooth_disabled': Icons.bluetooth_disabled,
    'bluetooth_searching': Icons.bluetooth_searching,
    'blur_circular': Icons.blur_circular,
    'blur_linear': Icons.blur_linear,
    'blur_off': Icons.blur_off,
    'blur_on': Icons.blur_on,
    'book': Icons.book,
    'bookmark': Icons.bookmark,
    'bookmark_border': Icons.bookmark_border,
    'bookmarks': Icons.bookmarks,
    'border_all': Icons.border_all,
    'border_bottom': Icons.border_bottom,
    'border_clear': Icons.border_clear,
    'border_color': Icons.border_color,
    'border_horizontal': Icons.border_horizontal,
    'border_inner': Icons.border_inner,
    'border_left': Icons.border_left,
    'border_outer': Icons.border_outer,
    'border_right': Icons.border_right,
    'border_style': Icons.border_style,
    'border_vertical': Icons.border_vertical,
    'branding_watermark': Icons.branding_watermark,
    'brightness_1': Icons.brightness_1,
    'brightness_2': Icons.brightness_2,
    'brightness_3': Icons.brightness_3,
    'brightness_4': Icons.brightness_4,
    'brightness_5': Icons.brightness_5,
    'brightness_6': Icons.brightness_6,
    'brightness_7': Icons.brightness_7,
    'brightness_auto': Icons.brightness_auto,
    'brightness_high': Icons.brightness_high,
    'brightness_low': Icons.brightness_low,
    'brightness_medium': Icons.brightness_medium,
    'broken_image': Icons.broken_image,
    'brush': Icons.brush,
    'bubble_chart': Icons.bubble_chart,
    'bug_report': Icons.bug_report,
    'build': Icons.build,
    'checkroom': Icons.checkroom,
    'burst_mode': Icons.burst_mode,
    'business': Icons.business,
    'business_center': Icons.business_center,
    'cached': Icons.cached,
    'cake': Icons.cake,
    'calendar_today': Icons.calendar_today,
    'calendar_view_day': Icons.calendar_view_day,
    'call': Icons.call,
    'call_end': Icons.call_end,
    'call_made': Icons.call_made,
    'call_merge': Icons.call_merge,
    'call_missed': Icons.call_missed,
    'call_missed_outgoing': Icons.call_missed_outgoing,
    'call_received': Icons.call_received,
    'call_split': Icons.call_split,
    'call_to_action': Icons.call_to_action,
    'camera': Icons.camera,
    'camera_alt': Icons.camera_alt,
    'camera_enhance': Icons.camera_enhance,
    'camera_front': Icons.camera_front,
    'camera_rear': Icons.camera_rear,
    'camera_roll': Icons.camera_roll,
    'cancel': Icons.cancel,
    'cancel_presentation': Icons.cancel_presentation,
    'card_giftcard': Icons.card_giftcard,
    'card_membership': Icons.card_membership,
    'card_travel': Icons.card_travel,
    'casino': Icons.casino,
    'cast': Icons.cast,
    'cast_connected': Icons.cast_connected,
    'category': Icons.category,
    'cell_wifi': Icons.cell_wifi,
    'center_focus_strong': Icons.center_focus_strong,
    'center_focus_weak': Icons.center_focus_weak,
    'change_history': Icons.change_history,
    'chat': Icons.chat,
    'chat_bubble': Icons.chat_bubble,
    'chat_bubble_outline': Icons.chat_bubble_outline,
    'check': Icons.check,
    'check_box': Icons.check_box,
    'check_box_outline_blank': Icons.check_box_outline_blank,
    'check_circle': Icons.check_circle,
    'check_circle_outline': Icons.check_circle_outline,
    'chevron_left': Icons.chevron_left,
    'chevron_right': Icons.chevron_right,
    'child_care': Icons.child_care,
    'child_friendly': Icons.child_friendly,
    'chrome_reader_mode': Icons.chrome_reader_mode,
    'class_': Icons.class_,
    'clear': Icons.clear,
    'clear_all': Icons.clear_all,
    'close': Icons.close,
    'closed_caption': Icons.closed_caption,
    'cloud': Icons.cloud,
    'cloud_circle': Icons.cloud_circle,
    'cloud_done': Icons.cloud_done,
    'cloud_download': Icons.cloud_download,
    'cloud_off': Icons.cloud_off,
    'cloud_queue': Icons.cloud_queue,
    'cloud_upload': Icons.cloud_upload,
    'code': Icons.code,
    'collections': Icons.collections,
    'collections_bookmark': Icons.collections_bookmark,
    'color_lens': Icons.color_lens,
    'colorize': Icons.colorize,
    'comment': Icons.comment,
    'compare': Icons.compare,
    'compare_arrows': Icons.compare_arrows,
    'compass_calibration': Icons.compass_calibration,
    'computer': Icons.computer,
    'confirmation_number': Icons.confirmation_number,
    'contact_mail': Icons.contact_mail,
    'contact_phone': Icons.contact_phone,
    'contactless': Icons.contactless,
    'contacts': Icons.contacts,
    'control_camera': Icons.control_camera,
    'control_point': Icons.control_point,
    'control_point_duplicate': Icons.control_point_duplicate,
    'copyright': Icons.copyright,
    'create': Icons.create,
    'create_new_folder': Icons.create_new_folder,
    'credit_card': Icons.credit_card,
    'crop': Icons.crop,
    'crop_16_9': Icons.crop_16_9,
    'crop_3_2': Icons.crop_3_2,
    'crop_5_4': Icons.crop_5_4,
    'crop_7_5': Icons.crop_7_5,
    'crop_din': Icons.crop_din,
    'crop_free': Icons.crop_free,
    'crop_landscape': Icons.crop_landscape,
    'crop_original': Icons.crop_original,
    'crop_portrait': Icons.crop_portrait,
    'crop_rotate': Icons.crop_rotate,
    'crop_square': Icons.crop_square,
    'dashboard': Icons.dashboard,
    'data_usage': Icons.data_usage,
    'date_range': Icons.date_range,
    'dehaze': Icons.dehaze,
    'delete': Icons.delete,
    'delete_forever': Icons.delete_forever,
    'delete_outline': Icons.delete_outline,
    'delete_sweep': Icons.delete_sweep,
    'departure_board': Icons.departure_board,
    'description': Icons.description,
    'desktop_mac': Icons.desktop_mac,
    'desktop_windows': Icons.desktop_windows,
    'details': Icons.details,
    'developer_board': Icons.developer_board,
    'developer_mode': Icons.developer_mode,
    'device_hub': Icons.device_hub,
    'device_unknown': Icons.device_unknown,
    'devices': Icons.devices,
    'devices_other': Icons.devices_other,
    'dialer_sip': Icons.dialer_sip,
    'dialpad': Icons.dialpad,
    'directions': Icons.directions,
    'directions_bike': Icons.directions_bike,
    'directions_boat': Icons.directions_boat,
    'directions_bus': Icons.directions_bus,
    'directions_car': Icons.directions_car,
    'directions_railway': Icons.directions_railway,
    'directions_run': Icons.directions_run,
    'directions_subway': Icons.directions_subway,
    'directions_transit': Icons.directions_transit,
    'directions_walk': Icons.directions_walk,
    'disc_full': Icons.disc_full,
    'dns': Icons.dns,
    'domain': Icons.domain,
    'domain_disabled': Icons.domain_disabled,
    'done': Icons.done,
    'done_all': Icons.done_all,
    'done_outline': Icons.done_outline,
    'donut_large': Icons.donut_large,
    'donut_small': Icons.donut_small,
    'double_arrow': Icons.double_arrow,
    'drafts': Icons.drafts,
    'drag_handle': Icons.drag_handle,
    'drag_indicator': Icons.drag_indicator,
    'drive_eta': Icons.drive_eta,
    'duo': Icons.duo,
    'dvr': Icons.dvr,
    'edit': Icons.edit,
    'edit_attributes': Icons.edit_attributes,
    'edit_location': Icons.edit_location,
    'eject': Icons.eject,
    'email': Icons.email,
    'emoji_events': Icons.emoji_events,
    'emoji_flags': Icons.emoji_flags,
    'emoji_food_beverage': Icons.emoji_food_beverage,
    'emoji_nature': Icons.emoji_nature,
    'emoji_people': Icons.emoji_people,
    'emoji_symbols': Icons.emoji_symbols,
    'emoji_transportation': Icons.emoji_transportation,
    'enhanced_encryption': Icons.enhanced_encryption,
    'equalizer': Icons.equalizer,
    'error': Icons.error,
    'error_outline': Icons.error_outline,
    'euro_symbol': Icons.euro_symbol,
    'ev_station': Icons.ev_station,
    'event': Icons.event,
    'event_available': Icons.event_available,
    'event_busy': Icons.event_busy,
    'event_note': Icons.event_note,
    'event_seat': Icons.event_seat,
    'exit_to_app': Icons.exit_to_app,
    'expand_less': Icons.expand_less,
    'expand_more': Icons.expand_more,
    'explicit': Icons.explicit,
    'explore': Icons.explore,
    'explore_off': Icons.explore_off,
    'exposure': Icons.exposure,
    'exposure_neg_1': Icons.exposure_neg_1,
    'exposure_neg_2': Icons.exposure_neg_2,
    'exposure_plus_1': Icons.exposure_plus_1,
    'exposure_plus_2': Icons.exposure_plus_2,
    'exposure_zero': Icons.exposure_zero,
    'extension': Icons.extension,
    'face': Icons.face,
    'fast_forward': Icons.fast_forward,
    'fast_rewind': Icons.fast_rewind,
    'fastfood': Icons.fastfood,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'featured_play_list': Icons.featured_play_list,
    'featured_video': Icons.featured_video,
    'feedback': Icons.feedback,
    'fiber_dvr': Icons.fiber_dvr,
    'fiber_manual_record': Icons.fiber_manual_record,
    'fiber_new': Icons.fiber_new,
    'fiber_pin': Icons.fiber_pin,
    'fiber_smart_record': Icons.fiber_smart_record,
    'file_copy': Icons.file_copy,
    'filter': Icons.filter,
    'filter_1': Icons.filter_1,
    'filter_2': Icons.filter_2,
    'filter_3': Icons.filter_3,
    'filter_4': Icons.filter_4,
    'filter_5': Icons.filter_5,
    'filter_6': Icons.filter_6,
    'filter_7': Icons.filter_7,
    'filter_8': Icons.filter_8,
    'filter_9': Icons.filter_9,
    'filter_9_plus': Icons.filter_9_plus,
    'filter_b_and_w': Icons.filter_b_and_w,
    'filter_center_focus': Icons.filter_center_focus,
    'filter_drama': Icons.filter_drama,
    'filter_frames': Icons.filter_frames,
    'filter_hdr': Icons.filter_hdr,
    'filter_list': Icons.filter_list,
    'filter_none': Icons.filter_none,
    'filter_tilt_shift': Icons.filter_tilt_shift,
    'filter_vintage': Icons.filter_vintage,
    'find_in_page': Icons.find_in_page,
    'find_replace': Icons.find_replace,
    'fingerprint': Icons.fingerprint,
    'first_page': Icons.first_page,
    'fitness_center': Icons.fitness_center,
    'flag': Icons.flag,
    'flare': Icons.flare,
    'flash_auto': Icons.flash_auto,
    'flash_off': Icons.flash_off,
    'flash_on': Icons.flash_on,
    'flight': Icons.flight,
    'flight_land': Icons.flight_land,
    'flight_takeoff': Icons.flight_takeoff,
    'flip': Icons.flip,
    'flip_camera_android': Icons.flip_camera_android,
    'flip_camera_ios': Icons.flip_camera_ios,
    'flip_to_back': Icons.flip_to_back,
    'flip_to_front': Icons.flip_to_front,
    'folder': Icons.folder,
    'folder_open': Icons.folder_open,
    'folder_shared': Icons.folder_shared,
    'folder_special': Icons.folder_special,
    'font_download': Icons.font_download,
    'format_align_center': Icons.format_align_center,
    'format_align_justify': Icons.format_align_justify,
    'format_align_left': Icons.format_align_left,
    'format_align_right': Icons.format_align_right,
    'format_bold': Icons.format_bold,
    'format_clear': Icons.format_clear,
    'format_color_fill': Icons.format_color_fill,

    'format_color_text': Icons.format_color_text,
    'format_indent_decrease': Icons.format_indent_decrease,
    'format_indent_increase': Icons.format_indent_increase,
    'format_italic': Icons.format_italic,
    'format_line_spacing': Icons.format_line_spacing,
    'format_list_bulleted': Icons.format_list_bulleted,
    'format_list_numbered': Icons.format_list_numbered,
    'format_list_numbered_rtl': Icons.format_list_numbered_rtl,
    'format_paint': Icons.format_paint,
    'format_quote': Icons.format_quote,
    'format_shapes': Icons.format_shapes,
    'format_size': Icons.format_size,
    'format_strikethrough': Icons.format_strikethrough,
    'format_textdirection_l_to_r': Icons.format_textdirection_l_to_r,
    'format_textdirection_r_to_l': Icons.format_textdirection_r_to_l,
    'format_underlined': Icons.format_underlined,
    'forum': Icons.forum,
    'forward': Icons.forward,
    'forward_10': Icons.forward_10,
    'forward_30': Icons.forward_30,
    'forward_5': Icons.forward_5,
    'free_breakfast': Icons.free_breakfast,
    'fullscreen': Icons.fullscreen,
    'fullscreen_exit': Icons.fullscreen_exit,
    'functions': Icons.functions,
    'g_translate': Icons.g_translate,
    'gamepad': Icons.gamepad,
    'games': Icons.games,
    'gavel': Icons.gavel,
    'gesture': Icons.gesture,
    'get_app': Icons.get_app,
    'gif': Icons.gif,
    'golf_course': Icons.golf_course,
    'gps_fixed': Icons.gps_fixed,
    'gps_not_fixed': Icons.gps_not_fixed,
    'gps_off': Icons.gps_off,
    'grade': Icons.grade,
    'gradient': Icons.gradient,
    'grain': Icons.grain,
    'graphic_eq': Icons.graphic_eq,
    'grid_off': Icons.grid_off,
    'grid_on': Icons.grid_on,
    'group': Icons.group,
    'group_add': Icons.group_add,
    'group_work': Icons.group_work,
    'hd': Icons.hd,
    'hdr_off': Icons.hdr_off,
    'hdr_on': Icons.hdr_on,
    'hdr_strong': Icons.hdr_strong,
    'hdr_weak': Icons.hdr_weak,
    'headset': Icons.headset,
    'headset_mic': Icons.headset_mic,
    'headset_off': Icons.headset_off,
    'healing': Icons.healing,
    'hearing': Icons.hearing,
    'help': Icons.help,
    'help_outline': Icons.help_outline,
    'high_quality': Icons.high_quality,
    'highlight': Icons.highlight,
    'highlight_off': Icons.highlight_off,
    'history': Icons.history,
    'home': Icons.home,
    'home_work': Icons.home_work,
    'hot_tub': Icons.hot_tub,
    'hotel': Icons.hotel,
    'hourglass_empty': Icons.hourglass_empty,
    'hourglass_full': Icons.hourglass_full,
    'house': Icons.house,
    'how_to_reg': Icons.how_to_reg,
    'how_to_vote': Icons.how_to_vote,
    'http': Icons.http,
    'https': Icons.https,
    'image': Icons.image,
    'image_aspect_ratio': Icons.image_aspect_ratio,
    'image_search': Icons.image_search,
    'import_contacts': Icons.import_contacts,
    'import_export': Icons.import_export,
    'important_devices': Icons.important_devices,
    'inbox': Icons.inbox,
    'indeterminate_check_box': Icons.indeterminate_check_box,
    'info': Icons.info,
    'info_outline': Icons.info_outline,
    'input': Icons.input,
    'insert_chart': Icons.insert_chart,
    'insert_chart_outlined': Icons.insert_chart_outlined,
    'insert_comment': Icons.insert_comment,
    'insert_drive_file': Icons.insert_drive_file,
    'insert_emoticon': Icons.insert_emoticon,
    'insert_invitation': Icons.insert_invitation,
    'insert_link': Icons.insert_link,
    'insert_photo': Icons.insert_photo,
    'invert_colors': Icons.invert_colors,
    'invert_colors_off': Icons.invert_colors_off,
    'iso': Icons.iso,
    'keyboard': Icons.keyboard,
    'keyboard_arrow_down': Icons.keyboard_arrow_down,
    'keyboard_arrow_left': Icons.keyboard_arrow_left,
    'keyboard_arrow_right': Icons.keyboard_arrow_right,
    'keyboard_arrow_up': Icons.keyboard_arrow_up,
    'keyboard_backspace': Icons.keyboard_backspace,
    'keyboard_capslock': Icons.keyboard_capslock,
    'keyboard_hide': Icons.keyboard_hide,
    'keyboard_return': Icons.keyboard_return,
    'keyboard_tab': Icons.keyboard_tab,
    'keyboard_voice': Icons.keyboard_voice,
    'kitchen': Icons.kitchen,
    'label': Icons.label,
    'label_important': Icons.label_important,
    'label_off': Icons.label_off,
    'landscape': Icons.landscape,
    'language': Icons.language,
    'laptop': Icons.laptop,
    'laptop_chromebook': Icons.laptop_chromebook,
    'laptop_mac': Icons.laptop_mac,
    'laptop_windows': Icons.laptop_windows,
    'last_page': Icons.last_page,
    'launch': Icons.launch,
    'layers': Icons.layers,
    'layers_clear': Icons.layers_clear,
    'leak_add': Icons.leak_add,
    'leak_remove': Icons.leak_remove,
    'lens': Icons.lens,
    'library_add': Icons.library_add,
    'library_books': Icons.library_books,
    'library_music': Icons.library_music,
    'line_style': Icons.line_style,
    'line_weight': Icons.line_weight,
    'linear_scale': Icons.linear_scale,
    'link': Icons.link,
    'link_off': Icons.link_off,
    'list': Icons.list,
    'list_alt': Icons.list_alt,
    'live_help': Icons.live_help,
    'live_tv': Icons.live_tv,
    'local_activity': Icons.local_activity,
    'local_airport': Icons.local_airport,
    'local_atm': Icons.local_atm,
    'local_bar': Icons.local_bar,
    'local_cafe': Icons.local_cafe,
    'local_car_wash': Icons.local_car_wash,
    'local_convenience_store': Icons.local_convenience_store,
    'local_dining': Icons.local_dining,
    'local_drink': Icons.local_drink,
    'local_florist': Icons.local_florist,
    'local_gas_station': Icons.local_gas_station,
    'local_grocery_store': Icons.local_grocery_store,
    'local_hospital': Icons.local_hospital,
    'local_hotel': Icons.local_hotel,
    'local_laundry_service': Icons.local_laundry_service,
    'local_library': Icons.local_library,
    'local_mall': Icons.local_mall,
    'local_movies': Icons.local_movies,
    'local_offer': Icons.local_offer,
    'local_parking': Icons.local_parking,
    'local_pharmacy': Icons.local_pharmacy,
    'local_phone': Icons.local_phone,
    'restaurant': Icons.restaurant,
    'local_pizza': Icons.local_pizza,
    'local_play': Icons.local_play,
    'local_post_office': Icons.local_post_office,
    'local_printshop': Icons.local_printshop,
    'local_see': Icons.local_see,
    'local_shipping': Icons.local_shipping,
    'local_taxi': Icons.local_taxi,
    'location_city': Icons.location_city,
    'location_disabled': Icons.location_disabled,
    'location_off': Icons.location_off,
    'location_on': Icons.location_on,
    'location_searching': Icons.location_searching,
    'lock': Icons.lock,
    'lock_open': Icons.lock_open,
    'look_out': Icons.lock_outline,
    'loop': Icons.loop,
    'loupe': Icons.loupe,
    'low_priority': Icons.low_priority,
    'loyalty': Icons.loyalty,
    'mail': Icons.mail,
    'mail_outline': Icons.mail_outline,
    'map': Icons.map,
    'markunread': Icons.markunread,
    'markunread_mailbox': Icons.markunread_mailbox,
    'maximize': Icons.maximize,
    'meeting_room': Icons.meeting_room,
    'memory': Icons.memory,
    'menu': Icons.menu,
    'merge_type': Icons.merge_type,
    'message': Icons.message,
    'mic': Icons.mic,
    'mic_none': Icons.mic_none,
    'mic_off': Icons.mic_off,
    'minimize': Icons.minimize,
    'missed_video_call': Icons.missed_video_call,
    'mms': Icons.mms,
    'mobile_screen_share': Icons.mobile_screen_share,
    'mode_comment': Icons.mode_comment,
    'monetization_on': Icons.monetization_on,
    'money': Icons.money,
    'money_off': Icons.money_off,
    'monochrome_photos': Icons.monochrome_photos,
    'mood': Icons.mood,
    'mood_bad': Icons.mood_bad,
    'more': Icons.more,
    'more_horiz': Icons.more_horiz,
    'more_vert': Icons.more_vert,
    'motorcycle': Icons.motorcycle,
    'mouse': Icons.mouse,
    'move_to_inbox': Icons.move_to_inbox,
    'movie': Icons.movie,
    'movie_creation': Icons.movie_creation,
    'movie_filter': Icons.movie_filter,
    'multiline_chart': Icons.multiline_chart,
    'music_note': Icons.music_note,
    'music_video': Icons.music_video,
    'my_location': Icons.my_location,
    'nature': Icons.nature,
    'nature_people': Icons.nature_people,
    'navigate_before': Icons.navigate_before,
    'navigate_next': Icons.navigate_next,
    'navigation': Icons.navigation,
    'near_me': Icons.near_me,
    'network_cell': Icons.network_cell,
    'network_check': Icons.network_check,
    'network_locked': Icons.network_locked,
    'network_wifi': Icons.network_wifi,
    'new_releases': Icons.new_releases,
    'next_week': Icons.next_week,
    'nfc': Icons.nfc,
    'no_encryption': Icons.no_encryption,
    'no_meeting_room': Icons.no_meeting_room,
    'no_sim': Icons.no_sim,
    'not_interested': Icons.not_interested,
    'not_listed_location': Icons.not_listed_location,
    'note': Icons.note,
    'note_add': Icons.note_add,
    'notes': Icons.notes,
    'notification_important': Icons.notification_important,
    'notifications': Icons.notifications,
    'notifications_active': Icons.notifications_active,
    'notifications_none': Icons.notifications_none,
    'notifications_off': Icons.notifications_off,
    'notifications_paused': Icons.notifications_paused,
    'offline_bolt': Icons.offline_bolt,
    'offline_pin': Icons.offline_pin,
    'ondemand_video': Icons.ondemand_video,
    'opacity': Icons.opacity,
    'open_in_browser': Icons.open_in_browser,
    'open_in_new': Icons.open_in_new,
    'open_with': Icons.open_with,
    'pages': Icons.pages,
    'pageview': Icons.pageview,
    'palette': Icons.palette,
    'pan_tool': Icons.pan_tool,
    'panorama': Icons.panorama,
    'panorama_fish_eye': Icons.panorama_fish_eye,
    'panorama_horizontal': Icons.panorama_horizontal,
    'panorama_vertical': Icons.panorama_vertical,
    'panorama_wide_angle': Icons.panorama_wide_angle,
    'party_mode': Icons.party_mode,
    'pause': Icons.pause,
    'pause_circle_filled': Icons.pause_circle_filled,
    'pause_circle_outline': Icons.pause_circle_outline,
    'payment': Icons.payment,
    'people': Icons.people,
    'people_outline': Icons.people_outline,
    'perm_camera_mic': Icons.perm_camera_mic,
    'perm_contact_calendar': Icons.perm_contact_calendar,
    'perm_data_setting': Icons.perm_data_setting,
    'perm_device_information': Icons.perm_device_information,
    'perm_identity': Icons.perm_identity,
    'perm_media': Icons.perm_media,
    'perm_phone_msg': Icons.perm_phone_msg,
    'perm_scan_wifi': Icons.perm_scan_wifi,
    'person': Icons.person,
    'person_add': Icons.person_add,
    'person_outline': Icons.person_outline,
    'person_pin': Icons.person_pin,
    'person_pin_circle': Icons.person_pin_circle,
    'personal_video': Icons.personal_video,
    'pets': Icons.pets,
    'phone': Icons.phone,
    'phone_android': Icons.phone_android,
    'phone_bluetooth_speaker': Icons.phone_bluetooth_speaker,
    'phone_forwarded': Icons.phone_forwarded,
    'phone_in_talk': Icons.phone_in_talk,
    'phone_iphone': Icons.phone_iphone,
    'phone_locked': Icons.phone_locked,
    'phone_missed': Icons.phone_missed,
    'phone_paused': Icons.phone_paused,
    'phonelink': Icons.phonelink,
    'phonelink_erase': Icons.phonelink_erase,
    'phonelink_lock': Icons.phonelink_lock,
    'phonelink_off': Icons.phonelink_off,
    'phonelink_ring': Icons.phonelink_ring,
    'phonelink_setup': Icons.phonelink_setup,
    'photo': Icons.photo,
    'photo_album': Icons.photo_album,
    'photo_camera': Icons.photo_camera,
    'photo_filter': Icons.photo_filter,
    'photo_library': Icons.photo_library,
    'photo_size_select_actual': Icons.photo_size_select_actual,
    'photo_size_select_large': Icons.photo_size_select_large,
    'photo_size_select_small': Icons.photo_size_select_small,
    'picture_as_pdf': Icons.picture_as_pdf,
    'picture_in_picture': Icons.picture_in_picture,
    'picture_in_picture_alt': Icons.picture_in_picture_alt,
    'pie_chart': Icons.pie_chart,
    'pin_drop': Icons.pin_drop,
    'place': Icons.place,
    'play_arrow': Icons.play_arrow,
    'play_circle_filled': Icons.play_circle_filled,
    'play_circle_outline': Icons.play_circle_outline,
    'play_for_work': Icons.play_for_work,
    'playlist_add': Icons.playlist_add,
    'playlist_add_check': Icons.playlist_add_check,
    'playlist_play': Icons.playlist_play,
    'plus_one': Icons.plus_one,
    'poll': Icons.poll,
    'polymer': Icons.polymer,
    'pool': Icons.pool,
    'portable_wifi_off': Icons.portable_wifi_off,
    'portrait': Icons.portrait,
    'power': Icons.power,
    'power_input': Icons.power_input,
    'power_settings_new': Icons.power_settings_new,
    'pregnant_woman': Icons.pregnant_woman,
    'present_to_all': Icons.present_to_all,
    'print': Icons.print,
    'print_disabled': Icons.print_disabled,
    'public': Icons.public,
    'publish': Icons.publish,
    'query_builder': Icons.query_builder,

    'question_answer': Icons.question_answer,
    'queue': Icons.queue,
    'queue_music': Icons.queue_music,
    'queue_play_next': Icons.queue_play_next,
    'radio': Icons.radio,
    'radio_button_checked': Icons.radio_button_checked,
    'radio_button_unchecked': Icons.radio_button_unchecked,
    'rate_review': Icons.rate_review,
    'receipt': Icons.receipt,
    'recent_actors': Icons.recent_actors,
    'record_voice_over': Icons.record_voice_over,
    'redeem': Icons.redeem,
    'redo': Icons.redo,
    'refresh': Icons.refresh,
    'remove': Icons.remove,
    'remove_circle': Icons.remove_circle,
    'remove_circle_outline': Icons.remove_circle_outline,
    'remove_from_queue': Icons.remove_from_queue,
    'remove_red_eye': Icons.remove_red_eye,
  };

  @override
  Widget build(BuildContext context) {
    // Filtra a lista de ícones baseado no que você digitou na busca
    final iconesFiltrados = _iconesDisponiveis.entries.where((entry) {
      return entry.key.toLowerCase().contains(_filtro.toLowerCase());
    }).toList();

    return Container(
      height: MediaQuery.of(context).size.height * 0.7, // Ocupa 70% da tela
      padding: const EdgeInsets.all(16.0),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Barra superior com título
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text('Selecione um Ícone', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              IconButton(icon: const Icon(Icons.close), onPressed: () => Navigator.pop(context)),
            ],
          ),
          const SizedBox(height: 8),

          // Campo de busca
          TextField(
            controller: _buscaController,
            decoration: InputDecoration(
              hintText: 'Pesquisar ícone (ex: store, car, food)...',
              prefixIcon: const Icon(Icons.search),
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
              contentPadding: const EdgeInsets.symmetric(vertical: 8),
            ),
            onChanged: (val) {
              setState(() {
                _filtro = val;
              });
            },
          ),
          const SizedBox(height: 16),

          // Grid com os ícones filtrados
          Expanded(
            child: iconesFiltrados.isEmpty
                ? const Center(child: Text('Nenhum ícone encontrado, uai!'))
                : GridView.builder(
                    gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 4, // 4 colunas de ícones
                      crossAxisSpacing: 12,
                      mainAxisSpacing: 12,
                    ),
                    itemCount: iconesFiltrados.length,
                    itemBuilder: (context, index) {
                      final nomeIcone = iconesFiltrados[index].key;
                      final iconeData = iconesFiltrados[index].value;

                      return InkWell(
                        onTap: () {
                          // 🎯 Retorna o codePoint (inteiro) e o nome para quem chamou a modal
                          widget.onIconeSelecionado(iconeData.codePoint, nomeIcone);
                          Navigator.pop(context); // Fecha a modal
                        },
                        borderRadius: BorderRadius.circular(12),
                        child: Container(
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey[300]!),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(iconeData, size: 30, color: const Color(0xFFE65100)),
                              const SizedBox(height: 4),
                              Text(nomeIcone, style: const TextStyle(fontSize: 10), textAlign: TextAlign.center, maxLines: 1, overflow: TextOverflow.ellipsis),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
